// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkh4CcGxHlwuik8SNro5433xjpSGpnFgk',
    appId: '1:360429077717:web:eace9f9cecd85a1cc28e5c',
    messagingSenderId: '360429077717',
    projectId: 'washer-v2-2cb9e',
    authDomain: 'washer-v2-2cb9e.firebaseapp.com',
    storageBucket: 'washer-v2-2cb9e.firebasestorage.app',
    measurementId: 'G-CWSWXM5GRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD663kBDeocLqzFdAabMLLLi-k5c9wBsQ',
    appId: '1:360429077717:android:75272bb69e1670cbc28e5c',
    messagingSenderId: '360429077717',
    projectId: 'washer-v2-2cb9e',
    storageBucket: 'washer-v2-2cb9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzEEQBvVj9Clw6CrYL2XrGBxh-9oxwIw',
    appId: '1:360429077717:ios:d49d6feca13ddb41c28e5c',
    messagingSenderId: '360429077717',
    projectId: 'washer-v2-2cb9e',
    storageBucket: 'washer-v2-2cb9e.firebasestorage.app',
    iosBundleId: 'com.washer.v2',
  );
}
